### PR TITLE
CI Testing

### PR DESCRIPTION
**Pull request by jjhursey**

### CODE REVIEW

**Comment by jjhursey** [comment]
bot:ibm:retest
bot:ibm:nodes:4:test

**Comment by jjhursey** [comment]
😞  it looks like we have a break. The command `prterun -n 4 --host localhost:4 hello 5` doesn't want to launch.

**Comment by jjhursey** [comment]
Seems to be something specific to specifying `localhost` for the hostname instead of the actual hostname.

**Comment by rhc54** [comment]
Fixed the "localhost" problem in https://github.com/openpmix/prrte/pull/1041

**Comment by jjhursey** [comment]
The attach case is failing while waiting for the application termination.

I _think_ that's because it is trying to wait for the application termination event, but only sees the lost_connection with prterun event. I'm not sure what needs to change. @drwootton or @rhc54 can you take a look at the mpishim.c code? Maybe there is something off with the `register_application_terminate_handler` function. Maybe it needs to be updated similar to some recent changes to the PRTE attach test case.

**Comment by drwootton** [comment]
Attach should be waiting for a lost connection event, not application termination. I will look at this tomorrow.

**Comment by jjhursey** [comment]
PR https://github.com/openpmix/mpir-to-pmix-guide/pull/12 should have fixed the attach case.
bot:ibm:retest

**Pull request closed without merging**
